---
- name: Ensure that flavors exists
  os_nova_flavor:
    cloud: "{{ openstack_cloud | default(omit) }}"
    auth: "{{ openstack_auth | default(omit) }}"
    verify: "{{ openstack_ssl_verify | default(true) }}"
    name: "{{ item.name }}"
    ram: "{{ item.ram }}"
    ephemeral: "{{ item.ephemeral | default(omit) }}"
    disk: "{{ item.disk }}"
    vcpus: "{{ item.vcpus }}"
    extra_specs: "{{ item.extra_specs | default(omit) }}"
    is_public: "{{ item.is_public | default(omit) }}"
    state: present
  loop: "{{ openstack_flavors }}"

- name: Enable access to the given flavor to project
  os_project_access:
    target_project_id: "{{ item.project_id }}"
    resource_name: "{{ item.name }}"
    resource_type: nova_flavor
  when: item.project_id is defined and item.project_id
  loop: "{{ openstack_flavors }}"
